### ISSUE TITLE
 System.Exception: IsiiSports.Pages.GamesPage, IsiiSports, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null not found

### ISSUE THREAD

**Issue by mrksoftware** [andrekiba/IsiiSports#1]
Sono riuscito a scaricare/buildare l'app, ma va in errore quando prova a creare i tab.
Magari ne sei già al corrente e stavi solo facendo delle prove.
Comunque ho risolto rispettando le conventions di FreshMvvm.
Fammi sapere se devo farti la pull request con tutte le views e viewsModel spostati sotto i namespace giusti

```
System.Exception: IsiiSports.Pages.GamesPage, IsiiSports, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null not found
   at FreshMvvm.FreshPageModelResolver.ResolvePageModel(Type type, Object data, FreshBasePageModel pageModel)
   at FreshMvvm.FreshPageModelResolver.ResolvePageModel[T](Object data, T pageModel)
   at FreshMvvm.FreshPageModelResolver.ResolvePageModel[T](Object initData)
   at FreshMvvm.FreshTabbedNavigationContainer.AddTab[T](String title, String icon, Object data)
   at IsiiSports.
```

**Comment by andrekiba** [comment]
Ciao Mirko ho sistemato grazie mille
